---
sidebar: sidebar 
permalink: concept-digital-wallet.html 
keywords: digital wallet, bluexp digital wallet, licensing, licenses, services, supported services 
summary: 'Das Digital Wallet von BlueXP ermöglicht das Management und Monitoring der von NetApp (BYOL), BlueXP Marketplace-Abonnements und von NetApp Keystone erworbenen BlueXP Lizenzen.' 
---
= Erfahren Sie mehr über das Digital Wallet von BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Das BlueXP  Digital Wallet ermöglicht das Management und Monitoring von BlueXP  Lizenzen, die über NetApp (BYOL), BlueXP  Data Services Marketplace-Abonnements (einschließlich NetApp Cloud Volumes ONTAP) und NetApp Keystone erworben wurden.



== Wie Lizenzen und Abonnements in der Digital Wallet angezeigt werden

Sowohl Lizenzen als auch Abonnements werden automatisch im Digital Wallet angezeigt, wenn es sich bei dem für die Anmeldung verwendeten BlueXP -Konto auch um ein NetApp Support-Website-Konto handelt. Wenn Sie ein BlueXP -Konto verwendet haben, das nicht mit Ihrem NSS-Konto (NetApp Support Site) verknüpft ist, müssen Sie Lizenzen manuell hinzufügen und aktualisieren, und die Nutzung, Kapazität und andere Details ändern sich nicht.


NOTE: Sie müssen einen Connector installiert haben, um Abonnementinformationen in der Digital Wallet anzuzeigen. Außerdem ist ein Connector erforderlich, um Node-Lizenzen für Cloud Volumes ONTAP anzuzeigen.

In der Zwischenzeit fragt BlueXP automatisch den NetApp Lizenzservice ab, um Informationen zu den Lizenzen zu erhalten, die mit Ihrem NetApp Support Site Konto verknüpft sind. Sollte es keine Fehler geben, fügt BlueXP die Lizenzen automatisch zum Digital Wallet hinzu.

Wenn BlueXP  die Lizenz nicht hinzufügen kann, müssen Sie sie manuell selbst in das Digital Wallet einfügen. Wenn Ihr BlueXP -Benutzerkonto beispielsweise nicht mit Ihrem NetApp Support-Website-Konto verknüpft ist, müssen Sie die Lizenzen selbst hinzufügen.

Nachdem Sie eine Lizenz bei Ihrem NetApp Vertriebsmitarbeiter erworben haben, erhalten Sie von NetApp eine E-Mail mit der Seriennummer und weiteren Lizenzierungsdetails. Sie benötigen diese Seriennummer, um die entsprechende Lizenz in der Digital Wallet hinzuzufügen oder zu aktualisieren.

https://docs.netapp.com/us-en/bluexp-setup-admin/task-adding-nss-accounts.html["Erfahren Sie, wie Sie BlueXP  Benutzerkennungen mit Ihrem Konto auf der NetApp Support Website ergänzen"^].



== Unterstützte Services

Mit dem BlueXP  Digital Wallet können Sie Lizenzen und Abonnements für die folgenden Services managen:

* https://docs.netapp.com/us-en/bluexp-backup-recovery/index.html["Backup und Recovery"^]
* https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^]
* https://docs.netapp.com/us-en/bluexp-disaster-recovery/index.html["Disaster Recovery"^] (Nur BYOL)
* https://docs.netapp.com/us-en/bluexp-ransomware-protection/index.html["Schutz durch Ransomware"^]
* https://docs.netapp.com/us-en/bluexp-ontap-onprem/index.html["ONTAP-Cluster vor Ort"^]
* https://docs.netapp.com/us-en/bluexp-tiering/index.html["Tiering"^]

