---
sidebar: sidebar 
permalink: concept-digital-wallet.html 
keywords: digital wallet, bluexp digital wallet, licensing, licenses, services, supported services 
summary: 'Das Digital Wallet von BlueXP ermöglicht das Management und Monitoring der von NetApp (BYOL), BlueXP Marketplace-Abonnements und von NetApp Keystone erworbenen BlueXP Lizenzen.' 
---
= Erfahren Sie mehr über das Digital Wallet von BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Das Digital Wallet von BlueXP ermöglicht das Management und Monitoring der von NetApp (BYOL), BlueXP Marketplace-Abonnements und von NetApp Keystone erworbenen BlueXP Lizenzen.



== Funktionen

* Management kapazitätsbasierter und Node-basierter Lizenzen für Cloud Volumes ONTAP
* Hinzufügen und Managen von Lizenzen für BlueXP Datenservices
* Abonnements für PAYGO- und Jahresverträge in Verbindung mit Ihrem BlueXP Konto und mit Astra Control managen
* Managen Sie die Keystone Abonnementservices zur Verwendung mit Cloud Volumes ONTAP und den On-Premises-ONTAP-Clustern und fordern Sie Änderungen an der gebuchten Kapazität an
* Statusinformationen zu Hardware- und Softwareverträgen für lokale ONTAP Cluster anzeigen




== Unterstützte Services

Mit dem Digital Wallet von BlueXP können Sie Lizenzen für die folgenden Services managen:

* https://docs.netapp.com/us-en/bluexp-backup-recovery/index.html["Backup und Recovery"^]
* https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^]
* https://docs.netapp.com/us-en/bluexp-disaster-recovery/index.html["Disaster Recovery"^] (Nur BYOL)
* https://docs.netapp.com/us-en/bluexp-ransomware-protection/index.html["Schutz durch Ransomware"^]
* https://docs.netapp.com/us-en/bluexp-ontap-onprem/index.html["ONTAP-Cluster vor Ort"^]
* https://docs.netapp.com/us-en/bluexp-tiering/index.html["Tiering"^]



TIP: Mit dem Digital Wallet von BlueXP  können Sie auch Lizenzen für die BlueXP -Klassifizierung managen. Allerdings ist die BlueXP -Klassifizierung als zentrale Funktion in BlueXP  jetzt ohne Zusatzkosten verfügbar. Eine Lizenz oder ein Abonnement ist nicht mehr erforderlich. https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["Weitere Informationen zur BlueXP Klassifizierung"^]
