---
settings:
  name: BlueXP digital wallet
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: de-de,us-en,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: BlueXP Digital-Wallet-Dokumente
    url: "/index.html"
  - title: Versionshinweise
    entries:
    - title: Was ist neu
      url: "/whats-new.html"
  - title: Los geht's
    entries:
    - title: Erfahren Sie mehr über das Digital Wallet von BlueXP
      url: "/concept-digital-wallet.html"
  - title: Nutzen Sie das Digital Wallet von BlueXP
    entries:
    - title: Verwenden Sie das Dashboard „Übersicht“
      url: "/task-homepage.html"
    - title: Lizenzen verwalten
      entries:
      - title: Verwaltung von Direktlizenzen
        url: "/task-manage-data-services-licenses.html"
      - title: Lizenzen für Cloud Volumes ONTAP verwalten
        entries:
        - title: Kapazitätsbasierte Lizenzen für Cloud Volumes ONTAP
          url: "/task-manage-capacity-licenses.html"
        - title: Node-basierte Lizenzen für Cloud Volumes ONTAP
          url: "/task-manage-node-based-licenses.html"
    - title: Marketplace-Abonnements verwalten
      url: "/task-manage-subscriptions.html"
    - title: Keystone Abonnements managen und
      url: "/task-manage-keystone.html"
    - title: Management von Lizenzen für On-Premises-ONTAP
      url: "/task-manage-on-prem-clusters.html"
    - title: Wissen und Support
      entries:
      - title: Für den Support anmelden
        url: "/task-support-registration.html"
      - title: Holen Sie sich Hilfe
        url: "/task-get-help.html"
    - title: Rechtliche Hinweise
      url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
