---
sidebar: sidebar 
permalink: task-manage-private-aws-cloud-insights.html 
keywords: activate,license, licensing, install, request capacity, link subscription, digital wallet, keystone flex, digital wallet, bluexp digital wallet 
summary: Verwalten Sie Ihren allgemeinen und Hyperscaler-spezifischen, durchgängigen Private Offer Process und die Akzeptanz- und Aktivierungsleitfäden für NetApp Intelligent Services für AWS, Azure und Google Cloud. 
---
= Akzeptieren und konfigurieren Sie ein privates AWS Marketplace-Angebot für NetApp Cloud Insights
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Akzeptieren Sie ein privates Marketplace-Angebot für NetApp Cloud Insights in der AWS-Konsole.  Verbinden Sie das AWS-Abonnement mit einer Cloud Insights -Arbeitsumgebung.

.Bevor Sie beginnen
* Arbeiten Sie mit dem NetApp -Vertrieb zusammen, um ein privates Angebot zu erstellen und den Angebotslink zu erhalten.
* Arbeiten Sie mit dem NetApp -Vertrieb zusammen, um eine Cloud Insights Arbeitsumgebung zu erstellen, und fügen Sie Ihre E-Mail mit der Rolle *Eigentümer* hinzu.
* Stellen Sie sicher, dass Sie über die erforderlichenlink:https://docs.aws.amazon.com/marketplace/latest/buyerguide/buyer-iam-users-groupspolicies.html["AWS Marketplace-Berechtigungen"]




== Akzeptieren Sie das private Angebot in der AWS-Konsole

[IMPORTANT]
====
Sie müssen alle Schritte abschließen, um Ihr privates Angebot zu aktivieren.  Das Überspringen von Schritten kann zu Aktivierungsproblemen oder Abrechnungsfehlern, einschließlich doppelter Abrechnung, führen.

====
.Schritte
. Klicken Sie auf den Aktivierungslink für das private Angebot, den Sie von Ihrem NetApp -Vertriebsteam erhalten haben.  Der Link sollte ungefähr wie folgt aussehen:
`https://aws.amazon.com/marketplace/saas/ordering?productId=aaa&offerId=offer-aaa`
+
[NOTE]
====
Wenn Sie keinen Aktivierungslink erhalten haben, können Sie alle privaten Angebote in der AWS-Konsole anzeigen.

** Erforderliche verwaltete Richtlinien: *AWSMarketplaceRead-only*, *AWSMarketplaceManageSubscriptions* oder *AWSMarketplaceFullAccess*
** Bei Verwendung benutzerdefinierter IAM-Richtlinien: `aws-marketplace:ListPrivateListings` Und `aws-marketplace:ViewSubscriptions`


====
. Sie werden zum AWS Marketplace weitergeleitet, um das private Angebot anzuzeigen und anzunehmen.
+
[NOTE]
====
Private Angebote werden zusätzlich zu öffentlichen Angeboten erstellt.  Verwenden Sie das Dropdown-Menü *Angebotsauswahl*, um zwischen öffentlichen und privaten Angeboten zu wechseln.

====
. Überprüfen Sie die Details des privaten Angebots und stellen Sie sicher, dass sie mit Ihrer Vereinbarung übereinstimmen.
+
.. Wenn die Informationen nicht korrekt sind, akzeptieren Sie sie nicht.  Wenden Sie sich an Ihr NetApp -Vertriebsteam, um das Angebot zu ändern.
.. Die Abrechnung beginnt, sobald Sie *Abonnieren* auswählen.
+
[NOTE]
====
In AWS gibt es zwei private Angebotstypen:

*** *On-Demand-Nutzung*
+
**** Preisinformationen
**** Rechtliche Hinweise


*** *Vertrag*
+
**** Dauer und Termine
**** Erneuerungseinstellungen
**** Vertragsoptionen
**** Gesamtvertragspreis




Bei Vertragsangeboten geben Sie bitte die vereinbarte Anzahl der zu verwaltenden Einheiten an.

====


. So nehmen Sie das private Angebot an:
+
.. Klicken Sie für die On-Demand-Nutzung auf *Abonnieren*.
.. Bei Vertragsangeboten geben Sie für jeden Service die Anzahl der verwalteten Einheiten ein und klicken auf *Vertrag erstellen*.


. Nach der Annahme bestätigt ein Banner Ihre erfolgreiche Anmeldung und bietet Informationen zu den nächsten Schritten.
. Klicken Sie auf *Konto einrichten*.  Dadurch werden Sie zu NetApp Cloud Insights weitergeleitet, um Ihr Marketplace-Abonnement zu konfigurieren.
+
[NOTE]
====
Wenn das Angebot angenommen, die Registrierung jedoch nicht abgeschlossen wurde, kehren Sie zur Produktseite zurück.  Sie werden aufgefordert, die Registrierung abzuschließen.

Klicken Sie bei Vertragsangeboten auf *Kaufoptionen anzeigen*, um das private Angebot anzuzeigen, und wählen Sie dann *Konto einrichten*.

====




== Verbinden des Abonnements mit Cloud Insights

.Schritte
. Sie werden weitergeleitet zu https://cloudinsights.netapp.com[] und aufgefordert, sich mit Ihrem BlueXP -Konto anzumelden.
. Melden Sie sich mit einem Konto an, das die Rolle *Eigentümer* hat.  Das Abonnement ist mit Ihrer Cloud Insights -Arbeitsumgebung verknüpft.
+
[NOTE]
====
Dieser Schritt ist für jedes Abonnement nur einmal erforderlich.  Verlängerungen und Add-Ons werden automatisch angewendet.

====
. Das Abonnement ist jetzt verbunden.

